In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [1]:
df = pd.read_csv("Social_Network_Ads.xls")

NameError: name 'pd' is not defined

In [4]:
df


User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
df.shape

(400, 5)

In [6]:
df.info

<bound method DataFrame.info of       User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]>

In [7]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [8]:
x = df.iloc[:,[2,3]].values

In [9]:
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [10]:
y = df.iloc[:,4].values

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [12]:
from sklearn.model_selection import train_test_split
(x_train,x_test,y_train,y_test) = train_test_split(x,y,test_size = 0.25)

In [13]:
x_train 

array([[    37,  72000],
       [    24,  32000],
       [    53,  82000],
       [    19,  85000],
       [    18,  52000],
       [    30, 116000],
       [    46,  28000],
       [    28,  37000],
       [    30,  87000],
       [    34,  43000],
       [    36,  75000],
       [    46,  96000],
       [    20,  36000],
       [    30, 135000],
       [    48,  35000],
       [    55, 130000],
       [    26,  84000],
       [    24,  27000],
       [    37,  77000],
       [    58,  23000],
       [    37,  78000],
       [    27,  57000],
       [    39, 134000],
       [    40,  78000],
       [    34, 115000],
       [    18,  82000],
       [    35,  39000],
       [    37,  80000],
       [    47,  43000],
       [    47,  30000],
       [    30, 107000],
       [    36, 125000],
       [    55,  39000],
       [    21,  88000],
       [    36,  99000],
       [    35,  97000],
       [    41,  87000],
       [    27,  96000],
       [    54,  26000],
       [    46,  22000],


In [14]:
x_train.shape

(300, 2)

In [16]:
y_test

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1])

In [17]:
y_test.shape

(100,)

In [18]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [19]:
y_train.shape

(300,)

In [22]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.fit_transform(x_test)

In [23]:
x_train

array([[-0.03954234,  0.03406796],
       [-1.29332372, -1.1406893 ],
       [ 1.50357321,  0.32775728],
       [-1.77554733,  0.41586407],
       [-1.87199205, -0.55331067],
       [-0.71465539,  1.32630095],
       [ 0.82846016, -1.25816503],
       [-0.90754483, -0.99384464],
       [-0.71465539,  0.47460193],
       [-0.3288765 , -0.81763105],
       [-0.13598706,  0.12217476],
       [ 0.82846016,  0.73892232],
       [-1.6791026 , -1.02321357],
       [-0.71465539,  1.88431065],
       [ 1.0213496 , -1.05258251],
       [ 1.69646265,  1.73746599],
       [-1.10043427,  0.38649514],
       [-1.29332372, -1.28753396],
       [-0.03954234,  0.18091262],
       [ 1.98579682, -1.40500968],
       [-0.03954234,  0.21028155],
       [-1.00398955, -0.40646601],
       [ 0.15334711,  1.85494172],
       [ 0.24979183,  0.21028155],
       [-0.3288765 ,  1.29693202],
       [-1.87199205,  0.32775728],
       [-0.23243178, -0.93510678],
       [-0.03954234,  0.26901941],
       [ 0.92490488,

In [24]:
x_train.shape

(300, 2)

In [25]:
x_test

array([[-0.87479364, -1.13570286],
       [ 1.82691195, -0.57449729],
       [ 0.14999124, -0.16097739],
       [ 1.4542629 ,  0.10485683],
       [-0.31582007, -0.16097739],
       [-1.15428042,  1.52263934],
       [ 0.2431535 , -0.45634875],
       [-1.52692947, -1.16524   ],
       [-0.9679559 ,  0.51837673],
       [ 0.70896481,  0.63652527],
       [ 0.98845159,  0.66606241],
       [-1.34060494, -0.3382002 ],
       [ 0.2431535 , -0.42681161],
       [-0.12949554, -0.98801719],
       [ 1.36110064,  0.1639311 ],
       [ 2.01323647, -0.95848005],
       [ 0.89528933,  2.20199346],
       [ 1.08161386, -1.37199995],
       [ 0.80212707, -1.37199995],
       [ 0.89528933,  0.22300537],
       [ 1.26793838, -1.34246281],
       [ 1.26793838,  1.4044908 ],
       [ 1.92007421,  0.48883959],
       [-0.31582007, -1.37199995],
       [ 0.05682898, -0.72218297],
       [-0.31582007, -1.16524   ],
       [ 0.14999124, -0.22005166],
       [ 0.89528933,  0.69559954],
       [-1.4337672 ,

In [26]:
x_test.shape

(100, 2)

In [27]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train,y_train)

LogisticRegression()

In [28]:
y_pred = classifier.predict(x_test)

In [29]:
y_pred

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1])

In [30]:
y_test

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1])

In [31]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[61,  5],
       [ 7, 27]])

In [33]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_pred) * 100
accuracy

88.0

In [37]:
tp = cm[0,[0]]
print(tp)

[61]


In [38]:
fp = cm[0,[1]]
print(fp)

[5]


In [39]:
fn = cm[1,[0]]
print(fn)

[7]


In [40]:
tn = cm[1,[1]]
print(tn)

[27]


In [43]:
accuracy_cm = ((tp+tn)/(tp+fp+fn+tn))
print(accuracy_cm * 100)

[88.]


In [44]:
error_rate = ((fp+fn)/(tp+fn+fn+tn))
print(error_rate * 100)

[11.76470588]


In [47]:
precision = ((tp)/(tp+fp))
precision * 100

array([92.42424242])

In [50]:
recall = (tp/(tp+fn))
recall * 100

array([89.70588235])

In [51]:
specificity = (tn/(fp+tn))
specificity * 100

array([84.375])